### ISSUE TITLE
Fine tune NER model

### ISSUE THREAD

**Issue by lizchow1** [AllanNastin/ethical-ai#55]

**Comment by faitholopade** [comment]
Get the label sentences we can use as fine tuning data. Once you have the data, you can begin fine tuning the BERT NER model. Erik gave in fine tuning code a while ago, you can try using that, but if it doesn't work, you can search online and definitely find some. You can also ask Dylan for help to set it up on a google colab.

**Comment by lizchow1** [comment]
Radnitz has made training data for BERT-Large model and currently attempting to train and fine tune the model
