### ISSUE TITLE
Find relation model

### ISSUE THREAD

**Issue by lizchow1** [AllanNastin/ethical-ai#7]

**Comment by faitholopade** [comment]
Finding a relation extraction model and code we can use. We're looking for something that takes in a NER output and/or text as input, and can output the relation mappings we can use as a knowledge graph. First read the resources Dylan has just put in. We ideally want to find and have a working model and code for next week. If your testing a model you may need input NER data, you can just download a ner model and run it on normal text to get a good sample for testing

**Comment by lizchow1** [comment]
https://github.com/AdirthaBorgohain/NER-RE
